[tool.poetry]
name = "scraping-tp-2"
version = "0.1.0"
description = ""
authors = ["Naoyuki Hirata <naoyuki.hirata.biz@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
